version: "2017-09-20"
dependencies:
- id: base
  type: docker
  ref: registry.opensource.zalan.do/stups/openjdk
pipeline:
- id: build
  overlay: ci/java
  type: script
  commands:
  - desc: Build JARs
    cmd: |
      # Test are performed by TravisCI
      mvn clean package -DskipTests
  - desc: Build and push Docker images
    cmd: |
      IMAGE=pierone.stups.zalan.do/torch/log-sink:${CDP_BUILD_VERSION}

      docker build --build-arg BASE_IMAGE_VERSION=${DEP_BASE_VERSION} --tag $IMAGE .

      if [ -z "$CDP_PULL_REQUEST_NUMBER" ]; then
        docker push $IMAGE
      fi
