management:
    # move all management endpoints to a different port
    port: 7979

endpoints:
    health:
        sensitive: false

spring:
    # JACKSON (JacksonProperties)
    jackson:
        property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
        date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
        serialization:
              write-dates-as-timestamps: false
        deserialization:
            fail-on-unknown-properties: false

security:
    user:
        name: ${USERNAME}
        password: ${PASSWORD}

#
# OAuth2
#
tokens:
    accessTokenUri: ${ACCESS_TOKEN_URI}
    credentialsDirectory: ${CREDENTIALS_DIR}

    token-configuration-list:
        - tokenId: logsink
          scopes:
              - uid

zuul:
  ignoredServices: '*'
  routes:
    instance-logs:
      path: /api/instance-logs/**
      url: ${FULLSTOP_URL}
      stripPrefix: false


hystrix:
  command:
    default:
      # https://github.com/Netflix/Hystrix/wiki/Configuration#CommandExecution
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

#logging:
#    level:
#      org.springframework.web: DEBUG
#      com.netflix.zuul: DEBUG
#      org.springframework.cloud: DEBUG
