management:
  # move all management endpoints to a different port
  port: 7979
  security:
    enabled: false

endpoints:
  health:
    sensitive: false

spring:
  # JACKSON (JacksonProperties)
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

#
# OAuth2
#
tokens:
  token-configuration-list:
  - tokenId: log-sink
    scopes:
    - uid

zuul:
  ignoredServices: '*'
  routes:
    instance-logs:
      path: /instance-logs

hystrix:
  command:
    default:
      # https://github.com/Netflix/Hystrix/wiki/Configuration#CommandExecution
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
  threadpool:
    default:
      maxQueueSize: 16
      queueSizeRejectionThreshold: 16

#logging:
#    level:
#      org.springframework.web: DEBUG
#      com.netflix.zuul: DEBUG
#      org.springframework.cloud: DEBUG
