management:
    # move all management endpoints to a different port
    port: 7979

endpoints:
    health:
        sensitive: false

spring:
    # JACKSON (JacksonProperties)
    jackson:
        property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
        date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
        serialization:
              write-dates-as-timestamps: false
        deserialization:
            fail-on-unknown-properties: false
    oauth2:
        resource:
            tokenInfoUri: ${TOKEN_INFO_URI}


#
# OAuth2
#
tokens:
    accessTokenUri: ${ACCESS_TOKEN_URI}
    credentialsDirectory: ${CREDENTIALS_DIR}

    token-configuration-list:
        - tokenId: logsink
          scopes:
              - uid

zuul:
  ignoredServices: '*'
  routes:
    instance-logs:
      path: /instance-logs/**
      url: ${FULLSTOP_URL}/api
      stripPrefix: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500
