tokens:
  token-configuration-list:
  - tokenId: log-sink
    scopes:
    - uid

zuul:
  ignoredServices: '*'
  routes:
    instance-logs:
      path: /instance-logs/**
      url: ${FULLSTOP_URL}


hystrix:
  command:
    default:
      # https://github.com/Netflix/Hystrix/wiki/Configuration#CommandExecution
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
  threadpool:
    default:
      maxQueueSize: 16
      queueSizeRejectionThreshold: 16

#logging:
#    level:
#      org.springframework.web: DEBUG
#      com.netflix.zuul: DEBUG
#      org.springframework.cloud: DEBUG
