tokens:
  use-existing-scheduler: false
  token-configuration-list:
    - tokenId: log-sink
      scopes:
        - uid

hystrix:
  command:
    default:
      # https://github.com/Netflix/Hystrix/wiki/Configuration#CommandExecution
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
  threadpool:
    default:
      maxQueueSize: 64
      queueSizeRejectionThreshold: 64

async:
  executor:
    core-pool-size: 8
    max-pool-size: 32
    queue-capacity: 16
    await-termination-seconds: 0

logbook:
    exclude:
        - /health
        - /metrics/**
    filter.enabled: true
    format.style: http
    obfuscate:
        headers:
            - Authorization
        parameters:
            - access_token
            - password

#logging:
#    level:
#      org.springframework.web: DEBUG
#      com.netflix.zuul: DEBUG
#      org.springframework.cloud: DEBUG
